<a href="https://colab.research.google.com/github/Raveen16/ABG-/blob/main/PRO_C126_Student_Boilerplate.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random

In [ ]:
def set_initial_state():
    return np.random.randint(0, 6)

In [ ]:
rewards = np.array([
    [-1, -1, -1, -1,  0,  -1],
    [-1, -1, -1,  0, -1, 100],
    [-1, -1, -1 , 0 ,-1 , -1],
    [-1,  0,  0 ,-1  ,-1 , -1],
    [0, -1, -1 , -1 ,-1 ,100],
    [-1, -1, -1, -1,  0, 100] 
])

In [ ]:
def get_action(current_state, reward_matrix):
    available_action = []
    print("reward_matrix","\n",reward_matrix)    
    for action in enumerate(reward_matrix[current_state]):     
        if action[1]!= -1:            
            available_action.append(action[0]) 
    choose_action = random.choice(available_action)
    print("Current State",current_state)
    print("Random choice of Action from",available_action,"is", choose_action)           
    return choose_action

In [ ]:
q_matrix = np.zeros([6,6])
print(q_matrix)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [ ]:
def take_action(current_state, reward_matrix, gamma):
    
    action = get_action(current_state, reward_matrix)
    
    #Current State, Action Reward
    current_sa_reward = reward_matrix[current_state, action]

    # New State, Action Reward
    q_sa_value = max(q_matrix[action,])
  
    # Current Q state
    q_current_state = current_sa_reward + (gamma * q_sa_value)

    # Update Q matrix
    q_matrix[current_state,action] = q_current_state
    
    print("q_matrix ","\n", q_matrix)

    new_state = action
    
    print("********************************************************************")
    
    if new_state == 5:
        print("Reached Goal!")
    else: 
        print(f"Old State:{current_state} New State: {new_state}")
        
    return new_state

## Train RL Model

Aim is to make the agent explore different states and reach the goal, the rewards are updated after each trial.

Agent completes an **episode** when it starts from initial state and reaches the goal.

For each action, Q-matrix is updated. This will act as the trained environment for the agent. Using the updated Q-matrix the agent can look for maximum reward and finds optimal path for any state.

Refer the link below to check how the episodes are run and Q-matrix is updated.
[Run Multiple Episodes](https://whitehatjrcontent.s3.ap-south-1.amazonaws.com/Teacher-Resources/COCOS_Applets/POC/Coding/SimpleQ-RL/final/index.html)

In [ ]:
def run_episode(initial_state,reward_matrix, gamma): 

    new_state =  take_action(initial_state, reward_matrix, gamma)

     # ADD CODE HERE ##

In [ ]:
def train(episodes, reward_matrix, gamma):
    print("Training...")
    
    # ADD CODE HERE ##
  


In [ ]:
gamma = 0.8

# Get Q table
q_table = train(2, rewards, gamma)

print("Final Q Table: ", q_table)

## Best Path to Goal

By looking at the q_table we find that the rewards are calculated for different states and actions. For a particular state the maximum rewards are given to the action which should be taken to find the optimal path to reach the goal.

In [ ]:
def optimal_path(q_table):
    path=[]
     # ADD CODE HERE ##

In [ ]:
Q_optimal_path, max_reward  = optimal_path(q_table)
print(Q_optimal_path, max_reward)